/**
 * The per-page <head> tags, the structured data and the sitemap, all built
 * from src/seo/routes.ts. The build (scripts/prerender.mjs) calls these;
 * seo.test.ts calls the same functions, so what is tested is what ships.
 */

import {
  MARKETING_ROUTES,
  NOT_FOUND_PAGE,
  SITE_ORIGIN,
  canonicalFor,
  type MarketingRoute,
} from "./routes";

/** Replaced in index.html by each page's own tags. */
export const HEAD_START = "<!-- page-head:start -->";
export const HEAD_END = "<!-- page-head:end -->";

const SOCIAL_IMAGE = `${SITE_ORIGIN}/social-preview.png`;

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Organization: who runs the site. `sameAs` lists only profiles that exist.
 * TODO(brandon): add the LinkedIn company URL and the YouTube channel URL here
 * once they exist; an empty list is left out rather than published.
 */
const SAME_AS: string[] = [];

export const ORGANIZATION_JSONLD = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Occupella",
  url: `${SITE_ORIGIN}/`,
  logo: `${SITE_ORIGIN}/icon-512.png`,
  ...(SAME_AS.length ? { sameAs: SAME_AS } : {}),
};

export const WEBSITE_JSONLD = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "Occupella",
  url: `${SITE_ORIGIN}/`,
};

/** `<` escaped so no string inside can close the script tag. */
function jsonLd(data: object): string {
  return `<script type="application/ld+json">${JSON.stringify(data).replace(/</g, "\\u003c")}</script>`;
}

export function headTags(route: MarketingRoute): string {
  const url = canonicalFor(route);
  const title = esc(route.title);
  const description = esc(route.description);
  return [
    HEAD_START,
    `<title>${title}</title>`,
    `<meta name="description" content="${description}" />`,
    `<link rel="canonical" href="${url}" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="Occupella" />`,
    `<meta property="og:title" content="${title}" />`,
    `<meta property="og:description" content="${description}" />`,
    `<meta property="og:url" content="${url}" />`,
    `<meta property="og:image" content="${SOCIAL_IMAGE}" />`,
    `<meta property="og:image:alt" content="The Occupella chat surface answering a question about a property." />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${title}" />`,
    `<meta name="twitter:description" content="${description}" />`,
    `<meta name="twitter:image" content="${SOCIAL_IMAGE}" />`,
    jsonLd(ORGANIZATION_JSONLD),
    jsonLd(WEBSITE_JSONLD),
    HEAD_END,
  ].join("\n    ");
}

/** The 404 page and the app shell: never indexed, no canonical. */
function unindexedHead(title: string, description: string): string {
  return [
    HEAD_START,
    `<title>${esc(title)}</title>`,
    `<meta name="description" content="${esc(description)}" />`,
    `<meta name="robots" content="noindex" />`,
    HEAD_END,
  ].join("\n    ");
}

export function notFoundHead(): string {
  return unindexedHead(NOT_FOUND_PAGE.title, NOT_FOUND_PAGE.description);
}

/**
 * The shell the setup wizard (/start) and the OAuth popup load into. It used
 * to be served for every URL, carrying the homepage's canonical; now it only
 * answers the client-only paths, and says nothing a search engine should keep.
 */
export function appShellHead(): string {
  return unindexedHead("Start your free trial | Occupella", "Set up Occupella.");
}

/**
 * The sitemap. `lastmod` comes from `lastmodFor` (the build reads each page's
 * last commit date) and is left out when unknown, never guessed: a lastmod
 * that changes on every deploy teaches Google to ignore it.
 */
export function sitemapXml(
  lastmodFor: (route: MarketingRoute) => string | undefined,
  routes: readonly MarketingRoute[] = MARKETING_ROUTES,
): string {
  const urls = routes.filter((r) => r.inSitemap).map((r) => {
    const lastmod = lastmodFor(r);
    return [
      "  <url>",
      `    <loc>${canonicalFor(r)}</loc>`,
      ...(lastmod ? [`    <lastmod>${lastmod}</lastmod>`] : []),
      `    <changefreq>${r.changefreq}</changefreq>`,
      `    <priority>${r.priority.toFixed(1)}</priority>`,
      "  </url>",
    ].join("\n");
  });
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/prerender.mjs from src/seo/routes.ts. Do not edit. -->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls,
    "</urlset>",
    "",
  ].join("\n");
}
